my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('api/', include('portfolio_api.urls')),
    path('', include('portfolio.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Мое портфолио'

users/urls.py
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                                      email_template_name="users/password_reset_email.html",
                                                      success_url=reverse_lazy("users:password_reset_done"),
                                                      extra_context={'title': 'Восстановление'}),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html",
                                                               extra_context={'title': 'Письмо отправлено'}),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete"),
                                          extra_context={'title': 'Новый пароль'}),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html",
                                           extra_context={'title': 'Пароль восстановлен'}),
         name='password_reset_complete'),

]

app_name = "users"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")

users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин",
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль",
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': "Имя",
            'last_name': "Фамилия",
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, required=False, label='E-mail',
                            widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(label='День рождения',
                                 widget=forms.SelectDateWidget(attrs={'class': 'date-birth'},
                                                               years=tuple(range(this_year - 100, this_year - 5))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'date_birth', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            'photo': forms.FileInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from my_portfolio import settings
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/user_form.html'
    extra_context = {'button': 'Войти', 'title': "Вход"}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:login')
    extra_context = {'button': 'Регистрация', 'title': "Регистрация"}


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = "users/profile.html"
    extra_context = {'title': "Профиль", 'button': 'Сохранить', 'default_image': settings.DEFAULT_USER_IMAGE}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/user_form.html"
    extra_context = {'title': "Изменение пароля", 'button': 'Сохранить'}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <form method="post" id="login-form">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit">Войти</button></p>
    </form>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="pass-reset-message">
        <h2>Пароль успешно изменен!</h2>
        <p></p>
        <a href="{% url 'users:profile' %}" class="back-link">>>> Вернуться в профиль</a>
    </div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" class="login-form">
        {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label> {{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit" class="lg-button">Сохранить</button></p>
    </form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="pass-reset-message">
        <h2>Сброс пароля</h2>

        <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

        <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
    </div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

    <form method="post" class="login-form">
        {% csrf_token %}
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label> {{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p><button type="submit" class="lg-button">Сбросить по E-mail</button></p>
    </form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <form method="post" id="profile-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user.photo %}
        <div class="user-photo"><img class="user-photo" src="{{ user.photo.url }}" alt="Фото пользователя"></div>
        {% else %}
        <div class="user-photo"><img class="user-photo" src="{{ default_image }}"
                                     alt="Фото пользователя по умолчанию"></div>
        {% endif %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="lg-button">{{ button }}</button></p>
        {% if not perms.users.social_auth %}
            <hr>
            <p><a href="{% url 'users:password_change' %}" class="change-pass-button">Сменить пароль</a></p>
        {% endif %}
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <form method="post" class="login-form">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        {% if title == "Вход" %}
            <p><a href="{% url 'social:begin' 'github' %}"><img src="/media/social-auth/gitgub_auth.png" width="7%"></a></p>
        {% endif %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="lg-button">{{ button }}</button></p>
        {% if title == "Вход" %}
            {% include 'users/for_include/reset_pass_button.html' %}
        {% endif %}
    </form>
{% endblock %}