my_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('api/', include('portfolio_api.urls')),
    path('', include('portfolio.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Мое портфолио'

users/urls.py
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                                      email_template_name="users/password_reset_email.html",
                                                      success_url=reverse_lazy("users:password_reset_done"),
                                                      extra_context={'title': 'Восстановление'}),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name="users/password_reset_done.html",
                                                               extra_context={'title': 'Письмо отправлено'}),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete"),
                                          extra_context={'title': 'Новый пароль'}),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html",
                                           extra_context={'title': 'Пароль восстановлен'}),
         name='password_reset_complete'),

]

app_name = "users"

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load portfolio_tags %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap-reboot.min.css">
    <script src="https://kit.fontawesome.com/43dac3556b.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'portfolio/images/papka.png' %}">
</head>
<body>
    <header class="main_header">
        <div class="logo">
            <img src="{% static 'portfolio/images/papka.png' %}" width="70px" alt="Логотип">
            <h1 class="text_logo">{{ title }}</h1>
        </div>
        <div class="main_menu">
            <ul class="top_menu">
                <li class="menu_link"><a href="{% url 'home' %}" class="mlink">Главная</a></li>
                <li class="menu_link"><a href="{% url 'contact' %}" class="mlink">Обратная связь</a></li>
                <li class="menu_link"><a href="{% url 'project' 'site-portfolio'%}" class="mlink">О сайте</a></li>
            </ul>
        </div>

        <div class="reg_men">
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <ul class="register_menu">
                            <li class="login-link lp"><a href="{% url 'users:profile' %}" class="mlink">{{user.username}}</a></li>
                            <li class="login-link cp">|</li>
                            <li class="login-link rp"><button type="submit" class="logout-button">Выйти</button></li>
                        </ul>
                    </form>
                {% else %}
                    <ul class="register_menu">
                        <li class="login-link lp"><a href="{% url 'users:login' %}" class="mlink">Войти</a></li>
                        <li class="login-link cp">|</li>
                        <li class="login-link rp"><a href="{% url 'users:register' %}" class="mlink">Регистрация</a></li>
                    </ul>
                {% endif %}
        </div>

    </header>

    <main class="main_main">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="main_footer">
        <div class="contacts">
            <div class="contacts-text"><h4>Контакты: </h4></div>
            <div class="contacts-blocks">
                <div class="social-networks">
                    <a href="https://github.com/Ksorran/My_portfolio"><img src="{% static 'portfolio/images/github_b.png'%}"
                                                                           alt="Логотип github" class="footer-1" width="12%"></a>
                    <a href="https://t.me/Evgeniy_Glushko"><img src="{% static 'portfolio/images/telegram.png' %}"
                                                                alt="Логотип telegram" class="footer-2" width="12%"></a>
                </div>
                <div class="telephone"><img src="{% static 'portfolio/images/white-telephone.png' %}" alt="Изображение телефона"
                                            class="telephone-logo"><span class="telephone-number">+7 965 083-15-34</span> </div>
            </div>
        </div>
        <div class="copyrights">© Все права защищены.</div>
    </footer>

</body>
</html>